In [72]:
# Just importing some stuffs

import tensorflow as tf 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import keras 
from keras.models import Sequential 
from keras.layers import Dense 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split

In [73]:
# Reading the csv file using pandas and giving it more functions and ease of use

data = pd.read_csv('heart.csv') 
data

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [74]:
data['cp']

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    0
1024    0
Name: cp, Length: 1025, dtype: int64

In [75]:
# data.describe() 


In [76]:
# Checking if there is any empty or null data in the dataset, so that it doesen't affect the model's performance

data.isnull().any() 

age         False
sex         False
cp          False
trestbps    False
chol        False
fbs         False
restecg     False
thalach     False
exang       False
oldpeak     False
slope       False
ca          False
thal        False
target      False
dtype: bool

In [77]:
# loading the data
# X contains input data (i.e: bp, cholesterol, sex......)
# Y contains output data  (i.e: yes or no, like if someone has heart disease or not)

# By combining these equations [f(x1, x2, x3) = y] or [f(bp, ch, sex) = heart disease is there or not]
# We can aquire a new equation or machine learning model that predicts the output



# X = data.iloc[:,:12].values 
y = data["target"].values

#                 age	sex   cp	trestbps	chol	fbs	  restecg thalach exang	oldpeak	slope	ca     thal	  target
X = data.iloc[:, [True, True, True,   True,     True,   True,  True,   True,  True,  False, False,  False, True,  False]].values 


In [78]:
X[0]

array([ 52,   1,   0, 125, 212,   0,   1, 168,   0,   3])

In [79]:
# Just printing the values stored in X and y

print("Input Values: ")
print(X)
print("\n", "-"*40, "\n")
print("Output Values: ")
print(y)

Input Values: 
[[ 52   1   0 ... 168   0   3]
 [ 53   1   0 ... 155   1   3]
 [ 70   1   0 ... 125   1   3]
 ...
 [ 47   1   0 ... 118   1   2]
 [ 50   0   0 ... 159   0   2]
 [ 54   1   0 ... 113   0   3]]

 ---------------------------------------- 

Output Values: 
[0 0 0 ... 0 1 0]


In [80]:
# Spliting the data into train and test (70% train, 30% test)

X_train,X_test,y_train, y_test = train_test_split(X,y,test_size = 0.1 , random_state = 0 ) 

In [81]:
# This is doing some shit which I didn't, but ig it is just shrinking the values ranging from -1 to 1
# What ever the value is it just shrinks it

from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() 
X_train = sc.fit_transform(X_train) 
X_test = sc.transform([[59, 1, 1, 140, 221, 0, 1, 164, 1, 2]]) 

In [82]:
# Ignore this

classifier = Sequential() 
classifier.add(Dense(activation = "relu", input_dim = 10, units = 8, kernel_initializer = "uniform")) 
classifier.add(Dense(activation = "relu", units = 14, kernel_initializer = "uniform")) 
classifier.add(Dense(activation = "sigmoid", units = 1, kernel_initializer = "uniform")) 
classifier.compile(optimizer = 'adam' , loss = 'binary_crossentropy', metrics = ['accuracy'] ) 


In [83]:
# Training the model

classifier.fit(X_train , y_train , batch_size = 8 ,epochs = 100 ) 


Epoch 1/100
116/116 [==============================] - 1s 3ms/step - loss: 0.6852 - accuracy: 0.6790
Epoch 2/100
116/116 [==============================] - 0s 2ms/step - loss: 0.5370 - accuracy: 0.7852
Epoch 3/100
116/116 [==============================] - 0s 2ms/step - loss: 0.4298 - accuracy: 0.7950
Epoch 4/100
116/116 [==============================] - 0s 2ms/step - loss: 0.4105 - accuracy: 0.8015
Epoch 5/100
116/116 [==============================] - 0s 3ms/step - loss: 0.4014 - accuracy: 0.8037
Epoch 6/100
116/116 [==============================] - 0s 3ms/step - loss: 0.3959 - accuracy: 0.8069
Epoch 7/100
116/116 [==============================] - 0s 3ms/step - loss: 0.3898 - accuracy: 0.8059
Epoch 8/100
116/116 [==============================] - 0s 4ms/step - loss: 0.3838 - accuracy: 0.8102
Epoch 9/100
116/116 [==============================] - 0s 3ms/step - loss: 0.3798 - accuracy: 0.8134
Epoch 10/100
116/116 [==============================] - 0s 2ms/step - loss: 0.3768 - accura

In [84]:
# save the model

classifier.save("models/model_X.h5")


In [44]:
from keras.models import load_model

classifier = load_model('models/model_Y.h5')


In [96]:
y_pred = classifier.predict(X_test) 
y_pred = (y_pred > 0.5) 

10/10 [==============================] - 0s 4ms/step
[0.40746713]


In [13]:
cm = confusion_matrix(y_test,y_pred) 
cm 

array([[133,  12],
       [ 20, 143]])

In [14]:
accuracy = (cm[0][0]+cm[1][1])/(cm[0][1] + cm[1][0] +cm[0][0] +cm[1][1]) 
print(accuracy*100) 


89.6103896103896


In [15]:
#tests only some 20 sample

count = 0

for i in y_pred:
    if i == True:
        print("Heart disease! (you will die soon)")
    else:
        print("No Heart disease! (you will die alone)")
        
    count+=1
    
    if count>20:
        break;

Heart disease! (you will die soon)
No Heart disease! (you will die alone)
No Heart disease! (you will die alone)
Heart disease! (you will die soon)
No Heart disease! (you will die alone)
No Heart disease! (you will die alone)
No Heart disease! (you will die alone)
No Heart disease! (you will die alone)
No Heart disease! (you will die alone)
No Heart disease! (you will die alone)
No Heart disease! (you will die alone)
No Heart disease! (you will die alone)
Heart disease! (you will die soon)
No Heart disease! (you will die alone)
Heart disease! (you will die soon)
Heart disease! (you will die soon)
Heart disease! (you will die soon)
No Heart disease! (you will die alone)
Heart disease! (you will die soon)
No Heart disease! (you will die alone)
Heart disease! (you will die soon)


In [30]:
len(X_train)+len(X_test)

1025

In [17]:
#print(data.to_string())


In [24]:
X_train[0]

array([ 0.27717522,  0.65226323,  1.02564169,  1.03903499, -1.51660781,
       -0.42111744,  0.92419637,  1.07403975, -0.7004602 , -0.51108759])

In [92]:
# load model

from keras.models import load_model
from sklearn.preprocessing import StandardScaler
import tensorflow as tf 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import keras 
from keras.models import Sequential 
from keras.layers import Dense 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split




data = pd.read_csv('heart.csv') 
X = data.iloc[:, [True, True, True,   True,     True,   True,  True,   True,  True,  False, False,  False, True,  False]].values 

dat = [[77, 0, 0, 110, 275, 0, 0, 118, 1, 2]] 

sc = StandardScaler() 


X_train = sc.fit_transform(X) 
dat = sc.transform(dat)


model = load_model('models/model_X.h5')

pred = model.predict(dat)
print(pred)
pred = (pred > 0.5)



1/1 [==============================] - 0s 38ms/step
[[0.2614653]]


In [71]:
if pred == False:
    print("No HD")

No HD
